### ISSUE TITLE
Convert .txt files to .pdf

### ISSUE THREAD

**Issue by itsikelis** [iloudaros/nomnomr#70]

**Comment by iloudaros** [comment]
Ποια txts ?

**Comment by itsikelis** [comment]
Πρέπει να γίνει μετατροπή όλων των .txt contributed αρχείων που μεταφέρθηκαν στην τελική αναφορά σε .pdf.

**Comment by iloudaros** [comment]
Γιατί ; 🤔

**Comment by itsikelis** [comment]
Μας ζητήθηκε από τον κύριο Ξένο.

**Comment by iloudaros** [comment]
Αφού το ζήτησε ο κύριος Ξένος μας 🥰. uwu, ara arah
